name:                updater
version:             0.1.0.0
github:              "nix-community/nix-vscode-extensions"
license:             BSD3
author:              "value"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/value/updater#readme>

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImplicitParams
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- NamedFieldPuns
- NumericUnderscores
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- http-client
- http-conduit
- aeson
- bytestring
- string-interpolate
- lens-aeson
- lens
- text
- time
- unordered-containers
- async
- generic-lens
- turtle
- http-types
- async-pool
- co-log-concurrent
- co-log
- stm
- stm-chans
- hashable
- mtl
- vector
- unliftio
- megaparsec
- yaml
- data-default
- versions

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  updater:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - updater