collectGarbage: true
logSeverity: Info
openVSX:
  pageCount: 1
  pageSize: 5
  nThreads: 5
  # release:
  #   eamodio:
  #     - gitlens
  #   rust-lang:
  #     - rust-analyzer
  #   stkb:
  #     - rewrap
vscodeMarketplace:
  pageCount: 0
  pageSize: 0
  # nThreads: 5
  # release:
  #   eamodio:
  #     - gitlens
  #   GitHub:
  #     - copilot
  #     - copilot-chat
  #     - vscode-pull-request-github
  #   ms-vscode-remote:
  #     - remote-ssh
  #   rust-lang:
  #     - rust-analyzer
  #   stkb:
  #     - rewrap
maxMissingTimes: 10
