[vadimcn--vscode-lldb--linux-x64]
src.github = "vadimcn/codelldb"
fetch.url = "https://github.com/vadimcn/codelldb/releases/download/$ver/codelldb-linux-x64.vsix"
passthru = { platform = "linux-x64", publisher = "vadimcn", name = "vscode-lldb", engineVersion = "^1.60.0" }
