# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vadimcn--vscode-lldb--darwin-arm64 = {
    pname = "vadimcn--vscode-lldb--darwin-arm64";
    version = "v1.11.1";
    src = fetchurl {
      url = "https://github.com/vadimcn/codelldb/releases/download/v1.11.1/codelldb-darwin-arm64.vsix";
      sha256 = "sha256-M4VYOmd72I8GAkRbeBztqbugrb4eHSotTUyrkmPmreA=";
    };
    publisher = "vadimcn";
    platform = "darwin-arm64";
    engineVersion = "^1.60.0";
    name = "vscode-lldb";
  };
  vadimcn--vscode-lldb--darwin-x64 = {
    pname = "vadimcn--vscode-lldb--darwin-x64";
    version = "v1.11.1";
    src = fetchurl {
      url = "https://github.com/vadimcn/codelldb/releases/download/v1.11.1/codelldb-darwin-x64.vsix";
      sha256 = "sha256-JHjIT84dDK7jCULe4YE3CAUNE+XFoFmwzsLJk4ktF44=";
    };
    publisher = "vadimcn";
    platform = "darwin-x64";
    engineVersion = "^1.60.0";
    name = "vscode-lldb";
  };
  vadimcn--vscode-lldb--linux-arm64 = {
    pname = "vadimcn--vscode-lldb--linux-arm64";
    version = "v1.11.1";
    src = fetchurl {
      url = "https://github.com/vadimcn/codelldb/releases/download/v1.11.1/codelldb-linux-arm64.vsix";
      sha256 = "sha256-FHoIqMiWBG8yxyqmVMHbebm44z19p+C1oYr9C3Z/hy8=";
    };
    publisher = "vadimcn";
    platform = "linux-arm64";
    engineVersion = "^1.60.0";
    name = "vscode-lldb";
  };
  vadimcn--vscode-lldb--linux-x64 = {
    pname = "vadimcn--vscode-lldb--linux-x64";
    version = "v1.11.1";
    src = fetchurl {
      url = "https://github.com/vadimcn/codelldb/releases/download/v1.11.1/codelldb-linux-x64.vsix";
      sha256 = "sha256-c8oVYihrJKHaHNM2uVBZnwSR+OtEfxYwtO/Qc9LMBlE=";
    };
    publisher = "vadimcn";
    platform = "linux-x64";
    engineVersion = "^1.60.0";
    name = "vscode-lldb";
  };
}
