name: Combine
on:
  workflow_call:
    inputs:
      TARGET:
        required: true
        type: string
      NUMBER_JOBS:
        required: true
        type: number

env:
  nixpkgs: nixpkgs=https://github.com/NixOS/nixpkgs/archive/cd87aef066e4bdbb1139845500072bd252d37c5e.tar.gz
  extra_nix_config: |
    substituters = https://cache.nixos.org https://nix-community.cachix.org https://fog.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fog.cachix.org-1:FAxiA6qMLoXEUdEq+HaT24g1MjnxdfygrbrLDBp6U/s=

  run_updater: export DENO_DIR=.deno && nix run nixpkgs#deno -- run --allow-write --allow-net={0} --no-prompt updater/index.ts {1} nvfetch/{2}.toml

  commit_and_push: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git config pull.rebase true
    let "N = ${{ inputs.NUMBER_JOBS }} + 1"
    git reset --soft HEAD~$N
    git add .
    git commit --allow-empty -m "action: update {0} extensions"
    git push -f

jobs:
  read_config:
    runs-on: ubuntu-latest
    outputs:
      combine: ${{ steps.combine.outputs.combine }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Combine
        id: combine
        run: echo "combine=$(jq -c . < .github/workflows/configs/${{ inputs.TARGET }}/combine.json)" >> $GITHUB_OUTPUT

  nvfetch:
    runs-on: ubuntu-latest
    needs: read_config
    strategy:
      matrix: ${{ fromJSON(needs.read_config.outputs.combine) }}
    steps:
      - name: Calculate fetch depth
        run: let 'a = ${{ inputs.NUMBER_JOBS }} + 2'; echo "FETCH_DEPTH=$a" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Git pull
        run: git pull
      - name: Install latest Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: ${{ env.extra_nix_config }}
          nix_path: ${{ env.nixpkgs }}

      - name: Combine extensions ${{ matrix.NAME }}
        env:
          TARGET: ${{ inputs.TARGET }}
        run: |
          nix run .#scripts.combine

      - name: Commit and push changes
        run: ${{ format(env.commit_and_push, inputs.TARGET) }}
